# Generated by Django 6.0.3 on 2026-03-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('filepath', models.CharField(max_length=1000, verbose_name='Caminho')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Última Modificação do Arquivo')),
                ('processed_at', models.DateTimeField(auto_now=True, verbose_name='Processado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Arquivo Excel',
                'verbose_name_plural': 'Arquivos Excel',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Aba')),
                ('sheet_index', models.IntegerField(default=0, verbose_name='Índice')),
                ('row_count', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('col_count', models.IntegerField(default=0, verbose_name='Total de Colunas')),
                ('headers', models.JSONField(default=list, verbose_name='Cabeçalhos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='core.excelfile', verbose_name='Arquivo Excel')),
            ],
            options={
                'verbose_name': 'Aba da Planilha',
                'verbose_name_plural': 'Abas da Planilha',
                'ordering': ['sheet_index'],
                'unique_together': {('excel_file', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('success', 'Sucesso'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('trigger', models.CharField(default='manual', max_length=50, verbose_name='Gatilho')),
                ('sheets_processed', models.IntegerField(default=0, verbose_name='Abas Processadas')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duração (seg)')),
                ('excel_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_history', to='core.excelfile', verbose_name='Arquivo Excel')),
            ],
            options={
                'verbose_name': 'Histórico de Sincronização',
                'verbose_name_plural': 'Histórico de Sincronizações',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Número da Linha')),
                ('data', models.JSONField(default=dict, verbose_name='Dados')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.excelsheet', verbose_name='Aba')),
            ],
            options={
                'verbose_name': 'Linha da Planilha',
                'verbose_name_plural': 'Linhas da Planilha',
                'ordering': ['row_number'],
                'unique_together': {('sheet', 'row_number')},
            },
        ),
    ]
