# Generated by Django 5.1.15 on 2026-03-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('registros_importados', models.IntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
                ('mensagem', models.TextField(blank=True)),
                ('abas_processadas', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Importação Excel',
                'verbose_name_plural': 'Importações Excel',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_pendente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('mes_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('competencia', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_nf', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('linha_planilha', models.IntegerField(blank=True, null=True)),
                ('aba_planilha', models.CharField(default='Sheet1', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
